/**
 * Build the syntax definition for Rust as a host language
 * @param {HostSpec} hostSpec - Specification for the host language
 * @param {EmbeddedSpec[]} embeddedSpecs - Array of data about each
 * embedded language
 * @returns {json} - Json object containing a TextMate language
 * injection
 */
export function buildNixSyntax(hostSpec, embeddedSpecs) {
    // Build the patterns that match each embedded language, using
    // a raw string with a start and stop marker
    // Example: /*sql*/ ''...''
    const embeddedPatterns = embeddedSpecs.map((lang) => {
        return {
            'comment': `${lang.name}-formatted strings`,

            'begin': String.raw`(/\*(?i:${lang.id_choice_re})\*/)\s*(\'\')`,
            'end': String.raw`\'\'(?!\$|\'|\\.)`,
            'contentName': `meta.embedded.block.${lang.vsname}.${hostSpec.vsname} ${lang.root_scope}`,
            'patterns': lang.embed_scopes.map((scope) => ({ 'include': scope })),
            'name': 'string.quoted.other.nix',
            'beginCaptures': {
                '1': { 'name': 'comment.block.nix' },
                '2': { 'name': 'punctuation.definition.string.other.start.nix' },
            },
            'endCaptures': {
                '0': { 'name': 'punctuation.definition.string.other.end.nix' },
            },
        };
    });

    // Build the overall grammar injection file, and include the
    // patterns from above
    const syntax = {
        '$schema': 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
        'injectionSelector': `L:source.nix -comment -string`,
        'scopeName': `${hostSpec.embedded_scope}`,
        'comment': `This file has been automatically generated by syntax_assembler.js
DO NOT HAND EDIT IT - changes will be lost.`,
        'patterns': [{ 'include': '#strings' }],
        'repository': {
            'strings': {
                'comment':
                    'These patterns all match Nix strings and select one language. The syntax is injected into ' +
                    'https://github.com/wmertens/sublime-nix/blob/master/nix.tmLanguage',
                'patterns': embeddedPatterns,
            },
        },
    };

    return syntax;
}

