/**
 * Build the syntax definition for Rust as a host language
 * @param {HostSpec} hostSpec - Specification for the host language
 * @param {EmbeddedSpec[]} embeddedSpecs - Array of data about each
 * embedded language
 * @returns {json} - Json object containing a TextMate language
 * injection
 */
export function buildRustSyntax(hostSpec, embeddedSpecs) {
    // Build the patterns that match each embedded language, using
    // a raw string with a start and stop marker
    // Example: /*sql*/ r#"..."#
    const embeddedPatterns = embeddedSpecs.map((lang) => {
        return {
            'comment': `${lang.name}-formatted raw strings`,

            'begin': String.raw`(/\*(?i:${lang.id_choice_re})\*/)\s*(b?r)(#*)(")`,
            'end': String.raw`(")(\3)`,
            'contentName': `meta.embedded.block.${lang.vsname}.${hostSpec.vsname} ${lang.root_scope}`,
            'patterns': [{ 'include': `${lang.root_scope}` }],
            'name': 'string.quoted.double.rust',
            'beginCaptures': {
                '1': { 'name': 'comment.block.rust' },
                '2': { 'name': 'string.quoted.byte.raw.rust' },
                '3': { 'name': 'punctuation.definition.string.raw.rust' },
                '4': { 'name': 'punctuation.definition.string.rust' },
            },
            'endCaptures': {
                '1': { 'name': 'punctuation.definition.string.rust' },
                '2': { 'name': 'punctuation.definition.string.raw.rust' },
            },

        };
    });

    // Build the overall grammar injection file, and include the
    // patterns from above
    const syntax = {
        '$schema': 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
        'injectionSelector': `L:source.rust -comment -string`,
        'scopeName': `${hostSpec.embedded_scope}`,
        'comment': `This file has been automatically generated by syntax_assembler.js
DO NOT HAND EDIT IT - changes will be lost.`,
        'patterns': [{ 'include': '#raw_strings' }],
        'repository': {
            'raw_strings': {
                'comment':
                    'These patterns all match Rust raw strings and select one language. The syntax is injected into ' +
                    'https://github.com/microsoft/vscode/blob/main/extensions/rust/syntaxes/rust.tmLanguage.json',
                'patterns': embeddedPatterns,
            },
        },
    };

    return syntax;
}

