/**
 * Build the syntax definition for Toml as a host language
 * @param {HostSpec} hostSpec - Specification for the host language
 * @param {EmbeddedSpec[]} embeddedSpecs - Array of data about each
 * embedded language
 * @returns {json} - Json object containing a TextMate language
 * injection
 */
export function buildTomlSyntax(hostSpec, embeddedSpecs) {
    // Build the patterns that match each embedded language, using an
    // internal comment. Skip languages that do not support comments.
    // Example: '''//cpp ...'''
    const patterns = embeddedSpecs.filter((embedded) => (embedded.comments.length > 0))
        .map((embedded) => ({
            'comment': `${embedded.name}-formatted triple-quoted strings`,
            'name': 'string.quoted.multi.embedded.toml',
            // Match only multiline literal strings - change the first
            // capture group to ('''|""") to match multiline basic
            // strings too
            'begin': String.raw`(?x)
(''') 
(?= (?i:${embedded.comment_choice_re}) \b )`,
            'end': String.raw`(\1)`,
            'contentName': `meta.embedded.block.${embedded.vsname}.${hostSpec.vsname} ${embedded.root_scope}`,
            'patterns': embedded.embed_scopes.map((scope) => ({ 'include': scope })),
            'beginCaptures': {
                '1': { 'name': 'punctuation.definition.string.begin.toml' },
            },
            'endCaptures': {
                '1': { 'name': 'punctuation.definition.string.end.toml' },
            },
        }));

    // Build the overall grammar injection file, and include the
    // patterns from above
    return {
        '$schema': 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
        'comment': `This file has been automatically generated by syntax_assembler.js
DO NOT HAND EDIT IT - changes will be lost.`,
        'injectionSelector': 'L:source.toml -string -comment',
        'scopeName': hostSpec.embedded_scope,
        'patterns': [{ 'include': '#triple_quoted_strings' }],
        'repository': {
            'triple_quoted_strings': {
                'comment': 'These patterns all match toml triple-quoted strings and select one language.' +
                    'The syntax is injected into https://github.com/oovm/vscode-toml/blob/master/extension/toml.tmLanguage.json',

                'patterns': patterns,
            },
        },
    };
}
